import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "payPal Services",
  description: "Generated by Mateen Nawaz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
